spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: embedded
      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#server:
#  error:
#    include-stacktrace: always