spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: embedded
      data-locations: db/data.sql
      schema-locations: db/schema.sql